
getgenv().Config = {
	["Select Pet Gift"] = {

	},
	["Select Pet Dont Delete"] = {
		["Brontosaurus"] = true,
		["Blood Owl"] = true,
		["Moon Cat"] = true,
		["T-rex"] = true,
		["French Fry Ferret"] = true,
		["Honey Bee"] = true,
		["Capybara"] = true,
		["Dilophosaurus"] = true,
		["Red Fox"] = true,
		["Fennec Fox"] = true,
		["Corrupted Kitsune"] = true,
		["Mimic Octopus"] = true,
		["Kitsune"] = true,
		["Chicken Zombie"] = true,
		["Spinosaurus"] = true,
		["Disco Bee"] = true,
		["Queen Bee"] = true,
		["Butterfly"] = true,
		["Dragonfly"] = true,
		["Raccoon"] = true,
		["Dog"] = true,
		["Echo Frog"] = true,
		["Starfish"] = true,
		["Night Owl"] = true,
		["Raiju"] = true,
		["Bunny"] = true,
		["Golden Lab"] = true
	},
	["Auto Rejoin"] = false,
	["Auto Cook Custom"] = false,
	["Auto Cook based on the Food requested by the NPC"] = true,
	["Use Save Position"] = true,
	["Auto Quest Prehistoric"] = false,
	["Select Rarity Pet Give Dinosaur"] = {
		["Rare"] = true
	},
	["Select Item Shop Merchant"] = {
		["Iconic Gnome Crate"] = true,
		["Sugar Apple"] = true,
		["Night Staff"] = true,
		["Kiwi Seed"] = true,
		["Bell Pepper Seed"] = true,
		["Pitcher Plant"] = true,
		["Classic Gnome Crate"] = true,
		["Bee Egg"] = true,
		["Avocado Seed"] = true,
		["Green Apple Seed"] = true,
		["Banana Seed"] = true,
		["Mutation Spray Verdant"] = true,
		["Common Gnome Crate"] = true,
		["Flower Seed Pack"] = true,
		["Mutation Spray Windstruck"] = true,
		["Pear Seed"] = true,
		["Mutation Spray Wet"] = true,
		["Feijoa Seed"] = true,
		["Loquat Seed"] = true,
		["Cantaloupe Seed"] = true,
		["Pineapple Seed"] = true,
		["Honey Sprinkler"] = true,
		["Prickly Pear Seed"] = true,
		["Mutation Spray Cloudtouched"] = true,
		["Star Caller"] = true,
		["Watermelon seed"] = true,
		["Farmers Gnome Crate"] = true
	},
	["Amount Set Idle"] = 100,
	["ESP Farm Player Other"] = false,
	["Save Position"] = {
		[1] = -21.071319580078125,
		[2] = -47.994476318359375,
		[3] = 0.3135833740234375
	},
	["Auto Give Fruit Kitsune"] = true,
	["Auto Give Tranquil For Panda"] = false,
	["Select Item Shop Zen"] = {
		["Zen Seed Pack"] = true,
		["Zen Egg"] = true
	},
	["Start ESP EGG"] = false,
	["Auto Load Script"] = true,
	["Auto Delete Sprinkler"] = false,
	["Auto Collect Egg"] = false,
	["Select Gear Use"] = "Godly Sprinkler",
	["Auto Delete Plant"] = false,
	["Enable if you dont know how to set idle"] = true,
	["Start Boost"] = false,
	["Auto Buy Egg"] = true,
	["Auto Delete Fruit"] = false,
	["Auto Set Pet Middle Farm Xp With Capybara"] = true,
	["Auto Craft"] = false,
	["Auto Sell"] = true,
	["Input Collect Summer Delay"] = 5,
	["Boost Fps"] = true,
	["Auto Buy Shop Summer"] = true,
	["Input Collect Summit Delay"] = 5,
	["Select Egg Plant"] = {
		["Bug Egg"] = true,
		["Common Summer Egg"] = true,
		["Dinosaur Egg"] = true,
		["Paradise Egg"] = true,
		["Gourmet Egg"] = true,
		["Primal Egg"] = true,
		["Night Egg"] = true,
		["Zen Egg"] = true,
		["Anti Bee Egg"] = true
	},
	["Auto Give Pet For Dinosaur"] = true,
	["Auto Delete Pet"] = true,
	["Auto Harvest Fruit Summer"] = true,
	["Webhook Profile"] = false,
	["Buy All Seed"] = true,
	["Auto Mutation Pet"] = false,
	["Auto Plant Egg"] = true,
	["Time Delay Set Idle"] = 0.1,
	["Auto Corrupt Channeller"] = true,
	["Auto Give Pollinated For Onett"] = true,
	["Select Sprinkler Delete"] = {
		["Godly Sprinkler"] = true
	},
	["Auto Collect Tranquil if Have"] = true,
	["Auto Plant Seed"] = true,
	["Select Item Craft"] = {
		["Anti Bee Egg"] = true,
		["Dinosaur Egg"] = true,
		["Primal Egg"] = true
	},
	["Ping Discord"] = false,
	["Delete Notification"] = false,
	["Select UUID Pet"] = {},
	["Auto Collect"] = true,
	["Auto Set Idle Pet"] = true,
	["Auto Gift"] = false,
	["Auto Buy Shop Honey"] = true,
	["Auto Buy Gear"] = true,
	["Auto Accept Gift"] = true,
	["Buy All Gear"] = true,
	["Fix Auto Gift In Delta"] = false,
	["Select Seed Plant"] = {
		["Pumpkin Seed"] = true,
		["Beanstalk Seed"] = true
	},
	["Auto Use Gear"] = true,
	["Select Item Shop Summer"] = {
		["Sugar Apple"] = true,
		["Oasis Egg"] = true,
		["Kiwi Seed"] = true,
		["Bell Pepper Seed"] = true,
		["Pitcher Plant"] = true,
		["Green Apple Seed"] = true,
		["Summer Seed Pack"] = true,
		["Pineapple Seed"] = true,
		["Watermelon seed"] = true,
		["Pear Seed"] = true,
		["Feijoa Seed"] = true,
		["Prickly Pear Seed"] = true,
		["Avocado Seed"] = true,
		["Cantaloupe Seed"] = true,
		["Banana Seed"] = true,
		["Loquat Seed"] = true,
		["Lily of the Valley Seed"] = true
	},
	["Spam Join"] = false,
	["Auto Give Food For NPC"] = true,
	["Auto Give Tranquil For Zen Channeller"] = true,
	["Start ESP"] = true,
	["Time Delay Gift"] = 1,
	["Webhook Collect Egg"] = true,
	["Auto Buy Shop Merchant"] = true,
	["Input Url Webhook"] = "https://discord.com/api/webhooks/1389864976491221064/lyhW_TJiq1-r_wJxqgGwJdipIKrA5e5s676YDzDpZps23MwX5FdSU-am3hVPJIzxF_nY",
	["Select Player Gift"] = "BP_Gamer03",
	["Auto Buy Seed"] = true,
	["Ignore Variant or Mutation"] = false,
	["Auto Use Boost XP Or Boost Passive Pet"] = true,
	["Auto Open Seed"] = true,
	["Auto Buy Shop Zen"] = true,
	["Boost FPS"] = true,
	["Input Slot Sell"] = 199,
	["Auto Feed Pet"] = true,
	["Select Name Plant Delete"] = {
		["Tomato"] = true
	},
	["Buy All Egg"] = true,
	["Auto Collect Pollinated if Have"] = true,
	["Select Item Shop Honey"] = {
		["Flower Seed Pack"] = true,
		["Bee Egg"] = true
	},
	["Auto Stack Idle Pet"] = false,
	["Save Position Plant Seed"] = {
		[1] = -21.62548828125,
		[2] = -47.994476318359375,
		[3] = -5.645530700683594
	}
}

-- Load script chính
loadstring(game:HttpGet("https://raw.githubusercontent.com/obiiyeuem/vthangsitink/main/BananaHub.lua"))()
